Replace SonarQube scan with Jacoco for code coverage
Removed SonarQube scan workflow and replaced it with Jacoco to generate coverage reports in the .github/workflows/test-pr.yml file. Also, added a step to check whether the coverage threshold is satisfied. The SonarQube scan related steps are commented out for future reference.

diff --git a/.github/workflows/test-pr.yml b/.github/workflows/test-pr.yml
--- a/.github/workflows/test-pr.yml
+++ b/.github/workflows/test-pr.yml
@@ -47,20 +47,33 @@ jobs:
       - name: Run integration tests
         run: ./gradlew integrationTest
 
-      - name: SonarQube Scan
-        run: ./gradlew sonar
-        env:
-          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
-          SONAR_ORG: ${{ secrets.SONAR_ORG }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      - name: Generate Coverage Report
+        run: mvn jacoco:report
 
-      - name: Quality Gate Check
-        id: quality_gate
+      - name: Check Coverage
         run: |
-          wget -q --wait=5 --tries=10 --retry-connrefused -O- "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status'
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          COVERAGE=$(mvn jacoco:report | grep -A 1 '<counter type="INSTRUCTION" missed="0" covered="' | grep 'covered' | sed -n 's/.*covered="\([0-9]*\)".*/\1/p')
+          THRESHOLD=80
+          if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
+            echo "Coverage is below threshold"
+            exit 1
+          fi
 
-      - name: Fail if Quality Gate failed
-        if: steps.quality_gate.outputs.result != 'OK'
-        run: exit 1
+
+#      - name: SonarQube Scan
+#        run: ./gradlew sonar
+#        env:
+#          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+#          SONAR_ORG: ${{ secrets.SONAR_ORG }}
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#
+#      - name: Quality Gate Check
+#        id: quality_gate
+#        run: |
+#          wget -q --wait=5 --tries=10 --retry-connrefused -O- "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status'
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#
+#      - name: Fail if Quality Gate failed
+#        if: steps.quality_gate.outputs.result != 'OK'
+#        run: exit 1
